trigger:
- main

variables:
- name: vmImageName
  value: ubuntu-latest

- name: tag
  value: $(Build.BuildId)

- name: imageRepository
  value: gs-spring-boot-docker

- name: dockerRegistryServiceConnection
  value: acr-connection   # <-- името което създаде

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    pool:
      vmImage: $(vmImageName)

    steps:

    - task: Maven@4
      displayName: Build Java app
      inputs:
        mavenPomFile: complete/pom.xml
        goals: package spring-boot:repackage

    - task: Docker@2
      displayName: Build and push image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: complete/Dockerfile
        buildContext: complete
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)